---
configs:
  ccloud_configs:
    api_key: "env::CCLOUD_API_KEY"
    api_secret: "env::CCLOUD_API_SECRET"
    ccloud_user: "env::CONFLUENT_CLOUD_EMAIL"
    ccloud_password: "env::CONFLUENT_CLOUD_PASSWORD"
    # enable_sa_cleanup: true
    detect_ignore_ccloud_internal_accounts: true
    ignore_service_account_list:
      - sa-xxxxx
      - sa-yyyyy
  secret_store:
    enabled: true
    type: aws-secretsmanager
    prefix: ""
    separator: "/"
    rest_proxy_secret_name: "rest_proxy_kafka_users"
    configs:
      - testing: "api_service"
      - secret_token: "api_pat_token"
